version: "3.9"
services:
  mysql:
    container_name: db
    image: gormerik/brew-monitor.db:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - data-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    env_file:
      - brew-monitor.Backend/db/db.env
    network_mode: host
  api:
    container_name: api
    image: gormerik/brew-monitor.api:latest
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - brew-monitor.Backend/api.env
    network_mode: host
  client:
    container_name: client
    image: gormerik/brew-monitor.client:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl:/etc/ssl
    network_mode: host
volumes:
  data-volume: