name: Deploy 
on:
  workflow_run:
    workflows: ["CI"]
  workflow_dispatch:
    branches:
      - master
        dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          config: |
            Host target
              HostName {{ secretes.HOST }}
              User {{ secrets.USERNAME }}
      #- name: Deploy
        #run: rsync -avz ${{ secrest.USERNAME }}@${{ secrets.SSH_HOST }}
      - name: Redeploy
        run: whoami
      
        #if: ${{ github.event.workflow_run.conclusion == 'success' }}
