name: Redeploy
on:
  workflow_dispatch:
    branches:
      - master
      - dev
jobs:
    redeploy:
        runs-on: ubuntu-latest
        steps:
            - name: ssh to host and run redeploy script
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: whoami
            
              #run: |
                  #cd /home/${{ secrets.USERNAME }}/brew-monitor/src
                  #git pull
                 # docker-compose down
                  
                  #docker pull ${{ secrets.USERNAME }}/brew-monitor.db
                  #docker pull ${{ secrets.USERNAME }}/brew-monitor.api
                  #docker pull ${{ secrets.USERNAME }}/brew-monitor.client
                  
                  #docker-compose up -d
