name: Deploy 
on:
  workflow_run:
    workflows: ["CI"]
  workflow_dispatch:
    branches:
      - master
        dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          ${{ secrets.PASSWORD }}
          whoami
        #with:
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          #script: whoami
