name: brew-monitor CI
on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    branches: 
      - dev
jobs:
  client_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
         context: .
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          driver: docker
          working-directory: src/brew-monitor.frontend_v2
          push: true
          dockerfile: ./Dockerfile
          repository: gormerik/brew-monitor.client
          tags: gormerik/brew-monitor.client:latest
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          driver: docker
          working-directory: src/brew-monitor.Backend
          dockerfile: ./Dockerfile
          push: true
          repository: gormerik/brew-monitor.api
          tags: gormerik/brew-monitor.api:latest

    
    
      
      
