name: brew-monitor CICD
on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    branches: 
      - dev
jobs:
  client_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        working-directory: src/brew-monitor.frontend
        run: docker build -t gormerik/brew-monitor.client .
      - name: Push
        run: docker push gormerik/brew-monitor.client
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        working-directory: src/brew-monitor.Backend
        run: docker build --build-arg DB_NAME=${{ secrets.DB_NAME}} --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} --build-arg DB_USER=${{ secrets.DB_USER }} -t gormerik/brew-monitor.api .
      - name: Push
        run: docker push gormerik/brew-monitor.api
