name: brew-monitor CI
on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
        dev
jobs:
  client_build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout client
        uses: actions/checkout@v2
      -
         name: DockerHub login
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           repository: gormerik/brew-monitor.client
      -
         name: Build and push
         uses: docker/build-push-action@v2
         with:
            working-directory: src/brew-monitor.frontend_v2
            file: ./Dockerfile
            push: true
            repository: gormerik/brew-monitor.client
            tags: gormerik/brew-monitor.client:latest
  backend_build:
    runs-on: ubuntu-latest
    steps:
      -
         name: Checkout backend
         uses: actions/checkout@v2
      - 
        name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: gormerik/brew-monitor.api
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          working-directory: src/brew-monitor.Backend
          file: ./Dockerfile
          push: true
          repository: gormerik/brew-monitor.api
          tags: gormerik/brew-monitor.api:latest

    
    
      
      
