name: brew-monitor CICD
on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    branches: 
      - dev
jobs:
  client_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        working-directory: src/brew-monitor.frontend_v2
        run: docker build -t gormerik/brew-monitor.client .
      - name: Push
        run: docker push gormerik/brew-monitor.client
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: src/brew-monitor.Backend/Dockerfile
          push: true
          tags: gormerik/brew-monitor.api:latest

    
    
      
      
