name: brew-monitor CICD
on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    branches: 
      - dev
jobs:
  client_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build client
        working-directory: src/brew-monitor.frontend_v2
        run: docker build -t gormerik/brew-monitor.client .
      - name: Push client
        run: docker push gormerik/brew-monitor.client
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build backend
        working-directory: src/brew-monitor.Backend
        run: docker build -t gormerik/brew-monitor.api .
      - name: Push backend
        run: docker push gormerik/brew-monitor.api

    
    
      
      
