name: Webhook 
on:
  workflow_run:
    workflows: ["CI"]
  workflow_dispatch:
    branches:
      - master
        dev
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook Action
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_ENDPOINT }}
